// Froggy Friends by Fonzy & Mayan (www.froggyfriendsnft.com) Stake Froggies

//...................................................@@@@@........................
//.......................%@@@@@@@@@*.............@@@@#///(@@@@@...................
//....................@@@&(//(//(/(@@@.........&@@////////////@@@.................
//....................@@@//////////////@@@@@@@@@@@@/////@@@@/////@@@..............
//..................%@@/////@@@@@(////////////////////%@@@@/////#@@...............
//..................@@%//////@@@#///////////////////////////////@@@...............
//..................@@@/////////////////////////////////////////@@@@..............
//..................@@(///////////////(///////////////(////////////@@@............
//...............*@@/(///////////////&@@@@@@(//(@@@@@@/////////////#@@............
//...............@@////////////////////////(%&&%(///////////////////@@@...........
//..............@@@/////////////////////////////////////////////////&@@...........
//..............@@(/////////////////////////////////////////////////@@#...........
//..............@@@////////////////////////////////////////////////@@@............
//...............@@@/////////////////////////////////////////////#@@/.............
//................&@@@//////////////////////////////////////////@@@...............
//..................*@@@%////////////////////////////////////@@@@.................
//...............@@@@///////////////////////////////////////(@@@..................
//............%@@@////////////////............/////////////////@@@................
//..........%@@#/////////////..................... (/////////////@@@..............
//.........@@@////////////............................////////////@@@.............
//........@@(///////(@@@................................(@@&///////&@@............
//.......@@////////@@@....................................@@@///////@@@...........
//......@@@///////@@@.......................................@@///////@@%..........
//.....(@@///////@@@.........................................@@/////(/@@..........

// SPDX-License-Identifier: MIT

pragma solidity ^0.8.13;

import "@openzeppelin/contracts/access/Ownable.sol";
import "hardhat/console.sol";

contract FriendPairing is Ownable {
  address public stakeFroggies;

  constructor(address _stakeFroggies) {
    stakeFroggies = _stakeFroggies;
  }

  function pairStakedFrog(
    uint256[] memory stakeFroggyIds
    // bytes32[][] memory stakeProof, 
    // uint256 pairFroggyId, 
    // bytes32[] memory pairProof, 
    // uint256 friendId
  ) public {
    // unstake frog
    (bool unstakeSuccess, bytes memory unstakeData) = stakeFroggies.delegatecall(
        abi.encodeWithSignature("unStake(uint256[])", stakeFroggyIds)
    );
    console.log("Unstake success %s", unstakeSuccess);
    // pair
    // (bool pairSuccess, bytes memory pairData) = stakeFroggies.delegatecall(
    //     abi.encodeWithSignature("pairFriend(uint256, bytes32[], uint256)", pairFroggyId, pairProof, friendId)
    // );

    // stake frog
    // (bool stakeSuccess, bytes memory stakeData) = stakeFroggies.delegatecall(
    //     abi.encodeWithSignature("stake(uint256[], bytes32[][])", stakeFroggyIds, stakeProof)
    // );
  }

  function pairUnstakedFrog(uint256 froggyId, bytes32[] memory proof, uint256 friend) public {

  }

  function setStakeFroggiesAddress(address _stakeFroggies) public onlyOwner {
    stakeFroggies = _stakeFroggies;
  }
}